export const categories = [
  {
    id: 1,
    name: "ice-cream",
    image: require("../assets/images/ice-cream.png"),
  },
  {
    id: 2,
    name: "ice",
    image: require("../assets/images/ice-cream.png"),
  },
  {
    id: 3,
    name: "tea",
    image: require("../assets/images/ice-cream.png"),
  },
  {
    id: 4,
    name: "chocolate",
    image: require("../assets/images/ice-cream.png"),
  },
  {
    id: 5,
    name: "burger",
    image: require("../assets/images/ice-cream.png"),
  },
  {
    id: 6,
    name: "sandwich",
    image: require("../assets/images/ice-cream.png"),
  },
]

export const featured = {
  id: 1,
  title: "hot and spicy",
  description: " soft and tender friend chiecken",
  restaurants: [
    {
      id: 1,
      name: "pizza shop",
      image: require("../assets/images/restaurant.png"),
      description: "hot spicy pizza",
      lng: 2.2944823551691775,
      lat: 48.85840879851614,
      address: "636 pizza street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza cheezy",
          description: "cheezy pizza",
          price: 10,
          image: require("../assets/images/pizza.png"),
        },
        {
          id: 2,
          name: "pizza meaty",
          description: "meaty pizza",
          price: 10,
          image: require("../assets/images/pizza.png"),
        },
        {
          id: 3,
          name: "pizza tomaty",
          description: "tomaty pizza",
          price: 10,
          image: require("../assets/images/pizza.png"),
        },
      ],
    },
    {
      id: 2,
      name: "chekin shop",
      image: require("../assets/images/restaurant.png"),
      description: "hot spicy chicken",
      lng:31.134267745564504,
      lat: 29.979265729194946,
      address: "636 chekin street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "chicken cheezy",
          description: "cheezy chicken",
          price: 10,
          image: require("../assets/images/pizza.png"),
        },
        {
          id: 2,
          name: "chicken meaty",
          description: "meaty chicken",
          price: 10,
          image: require("../assets/images/pizza.png"),
        },
        {
          id: 3,
          name: "chicken tomaty",
          description: "tomaty chicken",
          price: 10,
          image: require("../assets/images/pizza.png"),
        },
      ],
    },
    {
      id: 3,
      name: "Ice cream shop",
      image: require("../assets/images/restaurant.png"),
      description: "sweet ice cream",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "636 ice cream street",
      stars: 4,
      reviews: "4.4k",
      category: "sweets",
      dishes: [
        {
          id: 1,
          name: "cream chocolaty",
          description: "chocolaty ice cream",
          price: 5,
          image: require("../assets/images/ice-cream.png"),
        },
        {
          id: 2,
          name: "cream vanelly",
          description: "vanelly ice cream",
          price: 7,
          image: require("../assets/images/ice-cream.png"),
        },
        {
          id: 3,
          name: "cream banany",
          description: "banany ice cream",
          price: 15,
          image: require("../assets/images/ice-cream.png"),
        },
      ],
    },
  ],
}
